### ISSUE TITLE
Changes to the SDK API

### ISSUE THREAD

**Issue by andrascodes** [metastreet-labs/metastreet-sdk#56]
### TODO: Make separate issues for most of these so work is divided in reviewable chunks

- MetaStreetDeploymentProvider is only useful inside the BWLModal. For the BWLButton just use `useMetaStreetDeployment` and render the Tooltip with the "Unsupported chain" message if `deployment == undefined`.
---
- [ ] Export `useModalStateWithKey`. And rename it to `useBWLModalState()`, you can rename all the variables to `bwlModalOpen`, `openBWLModal`, `closeBWLModal`, `bwlModalKey` as well. So you don't have to do it all the time you destructure the return value of the hook.
---
- [ ] `useBuyWithLeverageButton(tokens: BWLToken[])` hook:
    - check for signer: `isWalletConnected`
    - check for `isSingleCollection`
    - `useIsCollectionSupported`
    - `useBWLModalState`
    - `useMetaStreetDeployment`
       - check for `deployment == undefined`, if so return "Unsupported chain" error
    - return:
        - `error`: new Error(<string error message>) for each boolean (isWalletConnected, isSingleCollection, isCollectionSupported, isUnsupportedChain?)
        - `isLoading`: from `useIsCollectionSupported` (expose the entire `useQuery` return value in that hook) - just enables the consumer to do what they want with the result
        - `data`: 
            - each boolean (isWalletConnected, isSingleCollection, isCollectionSupported, isUnsupportedChain). So consumers can customize the error message if they want.
            - value of `useBWLModalState`
            - can return `deployment` also
    - With all this the consumer can build their own button with whatever UI they want (in my case for `TokensGridBWLButton` the code would have been much cleaner)
---
- [ ] Modify `BuyWithLeverageButton` to use `useBuyWithLeverageButton`
    - One more idea: right now with the ErrorButton, LoadingButton it's not clear while looking at the code what is actually getting rendered (you have to look in the given components), you could have 1 return statement for all cases:
``` javascript
return (
    <Tooltip
      disable={!error}
      className={classNames("flex cursor-not-allowed", props.className)}
      trigger={
          <BaseBuyWithLeverageButton 
             disabled={error || loading} 
             className={classNames(className, {
                  "pointer-events-none w-full": error,
                  "disabled:cursor-wait": isLoading
              })}
              onClick={onClick}
          />
      }
      tooltipText={error}
    />
)
```

For `Tooltip` we can add a `disable` prop and `if(disable) return trigger`, this way we can "render" the Tooltip in the button but if we have to disable it it won't be added to the DOM

> Not going to lie if this becomes too complex, it's not much easier to grasp then having multiple components. But if we want to add transitions to this (button gets into loading state or error state) then it's impossible to do without having 1 render statement. To animate the Tooltip the `return trigger` solution also wouldn't work, we'd have to affect the `open` prop.
---
- [ ] Move all UI from SDK into the Marketplace and Trades Dash. We make our life easier if we include just the logic inside our SDK. Then we don't need to publish a new version to NPM and upgrade the package in the marketplace every time we need to make a copy or style change. Every consumer of the SDK will be writing their own UI anyway.
---
- [ ] Make BuyWithLeverageModal API better
