### ISSUE TITLE
SDK cleanup

### ISSUE THREAD

**Issue by aouahib** [metastreet-labs/metastreet-sdk#69]
#### 1. Modify API of current SDK
For now we can keep our Modal the same as it is now. It can have its own style and Modal. If anyone wants an unstyled modal we'll work with them to create a spec for it. This way there's also no need to create separate hooks for each UI component for now.

- [x] #70
    - check for signer: `isWalletConnected`
    - check for `isSingleCollection`
    - `useIsCollectionSupported`
    - `useBWLModalState`
    - `useMetaStreetDeployment`
       - check for `deployment == undefined`, if so return "Unsupported chain" error
    - return:
        - `error`: new Error(<string error message>) for each boolean (isWalletConnected, isSingleCollection, isCollectionSupported, isUnsupportedChain?)
        - `isLoading`: from `useIsCollectionSupported` (expose the entire `useQuery` return value in that hook) - just enables the consumer to do what they want with the result
        - `data`: 
            - each boolean (isWalletConnected, isSingleCollection, isCollectionSupported, isUnsupportedChain). So consumers can customize the error message if they want.
            - value of `useBWLModalState`
            - can return `deployment` also

- [x] Modify BuyWithLeverageButton so it uses `useBuyWithLeverageButton`

- [ ] Export `useModalStateWithKey`. And rename it to `useBWLModalState()`, you can rename all the variables to `bwlModalOpen`, `openBWLModal`, `closeBWLModal`, `bwlModalKey` as well. So you don't have to do it all the time you destructure the return value of the hook.

#### 2. Enable custom `graphApiKey`:
- [x] #72
    -  We need a context where the The Graph API key can be passed. This shouldn't check for Supported chain (`deployment == undefined`) that should only be done inside our Modal and in the `useBuyWithLeverageButton` hook.
    - Have our default decentralized subgraph URI in the deployment file, but also add an option to overwrite that (not just the API key)
- [x] #126

#### 3. Move all Trades Dash functionality into the SDK

- [x] #74

- [x] #76
- [x] #110
- [ ]  return `applyFees` and `exludeFees` from `useFees`
#### 4. Clean up the `test` app or create an `example` app
Can still be a Next app.

- [x] #137

- [x] #151
